name: learn-github-actions
on: [push]
jobs:
  test-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: test-python
        run: |
          python convert.py
      - name: first-artifact
        uses: actions/upload-artifact@v2
        with:
          name: convert_temp.md
          path: convert_temp.md
  convert-pdf:
    needs: test-python
    runs-on: ubuntu-latest
    container:
      image: pandoc/latex
      options: --entrypoint /bin/bash
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: download
        uses: actions/download-artifact@v2
        with:
          name: convert_temp.md
      - name: convert to pdf
        run: | 
          pandoc convert_temp.md -o convert_temp.pdf
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: convert_temp.pdf
          path: convert_temp.pdf
  
  push-pdf-to-repo:
    runs-on: ubuntu-latest
    needs: convert-pdf
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: download
        uses: actions/download-artifact@v2
        with:
          name: convert_temp.pdf
      - name: commit and push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          mv convert_temp.pdf $(date '+%Y-%m-%d' -d "3 days ago")-Data-Vis-Weekly.pdf
          git add .
          git commit -a -m "Automated Notes Build $(date '+%Y-%m-%d')"
          git push origin main


